import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../componentpages/Navbar'
import Content from '../componentpages/Content'
import Title from '../componentpages/Title'
import styled from '@emotion/styled'
import Footer from '../componentpages/Footer'

const Div = styled.div`
  display:flex;
  flex-direction:column;
  align-item:center;
  margin:auto;
  justify-content:center;
  width:85%
`

const Home: NextPage = () => {
  return (
    <>
      <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      </div>
      
      <Div>
        <NavBar/>
        <Title/>
        <Content/>
      </Div>
      <Footer/>
      
    </>
    
  )
}

export default Home
